// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCIid14g5IFy_1dXVBGXuAF5hDcRESAmk',
    appId: '1:671107708188:web:19e9638532baa25e4876d9',
    messagingSenderId: '671107708188',
    projectId: 'big-cart-6dd3c',
    authDomain: 'big-cart-6dd3c.firebaseapp.com',
    storageBucket: 'big-cart-6dd3c.firebasestorage.app',
    measurementId: 'G-RWQ4922PXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvBKXiQlNVDZ3u6djOUQOAroX_E15_Keg',
    appId: '1:671107708188:android:dbcd927e109d4cad4876d9',
    messagingSenderId: '671107708188',
    projectId: 'big-cart-6dd3c',
    storageBucket: 'big-cart-6dd3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5zuHg5hZDTZL2TENr3EOzFU9e-5ZMPnQ',
    appId: '1:671107708188:ios:ca7f9671d827bd334876d9',
    messagingSenderId: '671107708188',
    projectId: 'big-cart-6dd3c',
    storageBucket: 'big-cart-6dd3c.firebasestorage.app',
    iosBundleId: 'com.big.cart.bigCart',
  );
}
